stages:
 - build
 - test

build:precise:
  stage: build
  image: ubuntu:precise
  script:
    - apt install -y build-essential cmake coreutils sed \
        libreadline-dev libncurses5-dev libyaml-dev libssl-dev \
        libcurl4-openssl-dev libunwind-dev libicu-dev \
        python python-pip python-setuptools python-dev \
        python-msgpack python-yaml python-argparse python-six python-gevent
    - git submodule update --init --recursive
    - make clean
    - rm CMakeCache.txt
    - cmake .
    - make

build:trusty:
  stage: build
  image: ubuntu:trusty
  script:
    - apt install -y build-essential cmake coreutils sed \
          libreadline-dev libncurses5-dev libyaml-dev libssl-dev \
          libcurl4-openssl-dev libunwind-dev libicu-dev \
          python python-pip python-setuptools python-dev \
          python-msgpack python-yaml python-argparse python-six python-gevent
    - git submodule update --init --recursive
    - make clean
    - rm CMakeCache.txt
    - cmake .
    - make
